name: Release

on:
  push:
    tags: ['v*']

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    permissions:
      # permission for creating a GitHub release
      contents: write
      # permission for publishing to npm with provenance
      id-token: write
    # env:
    #   tag: ${{ github.ref_name }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        # with: { ref: main }

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with: { version: 10.17.0 }

      - name: Install dependencies
        run: pnpm install

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}
        run: |
          echo "Tag is $tag"
          gh release create $tag \
            --title $tag \
            --notes "Release $tag" \
            --draft

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --provenance --access public